apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-assessment-staticassets
  labels:
    app: assessment-staticassets
spec:
  replicas: {{ .Values.staticassets.replicaCount }}
  selector:
    matchLabels:
      app: assessment-staticassets
  template:
    metadata:
      labels:
        app: assessment-staticassets
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.staticassets.image.repository }}:{{ .Values.staticassets.image.tag }}"
          imagePullPolicy: {{ .Values.staticassets.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            {{- toYaml .Values.staticassets.resources | nindent 12 }}
      {{- with .Values.staticassets.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.staticassets.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.staticassets.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
