apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "assessment-chart-template.fullname" . }}-assessment-frontend
  labels:
    app.kubernetes.io/name: {{ include "assessment-chart-template.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "assessment-chart-template.chart" . }}
    app.kubernetes.io/component: assessment-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "assessment-chart-template.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: assessment-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "assessment-chart-template.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: assessment-frontend
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            {{- with (index .Values.staticassets.ingress.hosts 0) }}
            - name: STATIC_URL
              value: http://{{ .host }}
            {{- end }}
            - name: QUOTE_SERVICE_URL
              value: http://{{ .Release.Name }}-quotes-service:8081
            - name: NEWSFEED_SERVICE_URL
              value: http://{{ .Release.Name }}-newsfeed-service:8082
            - name: NEWSFEED_SERVICE_TOKEN
              value: 'T1&eWbYXNWG1w1^YGKDPxAWJ@^et^&kX'
          readinessProbe:
            httpGet:
              path: /ping
              port: http
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
