apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-newsfeed-service
spec:
  selector:
    app: assessment-newsfeed
  type: {{ .Values.newsfeed.service.type }}
  ports:
    - protocol: {{ .Values.newsfeed.service.protocol | default "TCP" }}
      port: {{ .Values.newsfeed.service.port }}
      targetPort: {{ .Values.newsfeed.service.targetPort }}